---
- hosts: all
  collections:
  - anisble.windows

  tasks:
  - name: Get whoami information
    ansible.windows.win_whoami:

  - name: Create a local group
    win_group:
      name: Ansibledemo_group
      description: Ansible demo

  - name: Create some local users 
    win_user:
      name: '{{ item.name }}'
      password: '{{ item.password }}'
      groups: Ansibledemo_group
      update_password: Always
      password_never_expires: false
      account_locked: no
    loop:
    - name: Ansibledemo1
      password: "{{ user_password }}"
    - name: Ansibledemo2
      password: "{{ user_password }}"
