- name: Set the state of a virtual machine to poweroff
  community.vmware.vmware_guest_powerstate:
    # folder: "/{{ datacenter_name }}/vm/my_folder"
    name: "{{ guest_name }}"
    state: powered-off
  delegate_to: localhost
