---
- hosts: localhost
  collections:
    - community.vmare

  gather_facts: false

  vars:
    vmware:
      hostname: '{{ lookup("env", "VMWARE_HOST" }}'
      username: '{{ lookup("env", "VMWARE_USER" }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD" }}'

  tasks:
    - include_tasks: tasks/reboot_vm.yaml
