---
- hosts: localhost
  collections:
    - netapp.storagegrid

  vars:
    - grid_admin_base_url: "https://10.5.162.121/"
 
  tasks:
    - include_tasks: tasks/get_all_buckets.yaml
    - include_tasks: tasks/check_duplicate_bucketname.yaml
    - include_tasks: tasks/create_tenant.yaml
    - include: tasks/create_bucket.yaml
    - include: tasks/create_keys.yaml
