---
- hosts: localhost
  collections:
  - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ ontap_system }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      
  tasks:
  - name:  Create Volume
    na_ontap_volume:
      state: present
      name: "{{ item.volume }}"
      size: "{{ item.volume_size }}"
      size_unit: "{{ item.volume_size_unit }}"
      vserver: "{{ item.vserver }}"
      aggregate_name: "{{ item.aggregate_name }}"
    loop:
      - { volume: 'vol01', volume_size: '300', volume_size_unit: 'mb', vserver: 'semsi', aggregate_name: 'ssd01' }
      - { volume: 'vol02', volume_size: '400', volume_size_unit: 'mb', vserver: 'semsi', aggregate_name: 'ssd02' }
      - { volume: 'vol03', volume_size: '450', volume_size_unit: 'mb', vserver: 'semsi', aggregate_name: 'ssd02' }
