---
- hosts: localhost
  collections:
  - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: 10.5.160.212
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      
  name: Onboard SVM
  tasks:
  - name:  Create Volume
    na_ontap_volume:
      state: present
      name: "{{ item.volume }}"
      size: "{{ item.volume_size }}"
      size_unit: "{{ item.volume_size_unit }}"
      vserver: "{{ item.vserver }}"
      aggregate_name: "{{ item.aggregate_name }}"
      policy: "{{ policy }}"
    loop:
      - { volume: 'vol5', volume_size: '20', volume_size_unit: 'mb', vserver: 'ansibleSVM', aggregate_name: 'ssd01' }
