---
- hosts: localhost
  collections:
  - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ ontap_system }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      
  tasks:
  - name: create or modify s3 user
    na_ontap_s3_users:
      state: present
      name: martin1
      vserver: s3svm01
      comment: not enabled
      https: true
      validate_certs: false
      use_rest: always
      
  - name: Create and modify a S3 Group
    netapp.ontap.na_ontap_s3_groups:
      state: present
      name: dev-group
      comment: group for devs
      vserver: s3svm01
      users:
        - name: martin1
      policies:
        - name: FullAccess
      https: true
      validate_certs: false
      use_rest: always
