---
- hosts: localhost
  collections:
  - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ ontap_system }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      
  tasks:
  - name: Create ONTAP/ONTAP vserver SnapMirror
    netapp.ontap.na_ontap_snapmirror:
      state: present
      source_vserver: ansibleSVM
      destination_vserver: semsi
      identity_preserve: true

  - name: Inititalize ONTAP/ONTAP SnapMirror
    netapp.ontap.na_ontap_snapmirror:
      state: present
      source_path: 'ansibleSVM:martintest1'
      destination_path: 'semsi:martintest1_dest'
      relationship_state: active

