---
- hosts: localhost
  collections:
  - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ ontap_system }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      
  tasks:
  - name: Create SnapMirror relationship (create destination volume)
    tags: create
    netapp.ontap.na_ontap_snapmirror:
      state: present
      source_endpoint:
        cluster: "{{ _source_cluster }}"
        path: "{{ source_vserver + ':' + source_volume }}"
      destination_endpoint:
        cluster: "{{ _destination_cluster }}"
        path: "{{ destination_vserver + ':' + destination_volume }}"
      create_destination:
        enabled: true
