---
- hosts: localhost
  collections:
  - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ ontap_system }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      
  tasks:
  - name: create SnapShot
    tags:
      - create
    netapp.ontap.na_ontap_snapshot:
      state: present
      snapshot: "mittdemosnap"
      volume: "vol01"
      comment: "i am a snaphot"
      expiry_time: "2024-05-05T14:00:00-05:00"
      vserver: "semsi"
