- name: Get user authorization token for Tenant
  uri:
    url: "{{ grid_admin_base_url }}/api/v3/authorize"
    method: POST
    body: {
      "accountId": "{{ tenant_id }}",
      "username": "{{ storagegrid_login_username }}",
      "password": "{{ storagegrid_login_password }}",
      "cookie": false,
      "csrfToken": false
    }
    body_format: json
    validate_certs: false
  register: auth
    
- name: create a s3 key
  netapp.storagegrid.na_sg_org_user_s3_key:
    api_url: "{{ grid_admin_base_url }}"
    auth_token: "{{ auth.json.data }}"
    validate_certs: false
    state: present
    expires: "{{ ansible_date_time.year | int + 3 }}-{{ ansible_date_time.month }}-{{ ansible_date_time.day }}T{{ ansible_date_time.time }}"
    unique_user_name: user/user1
  register: keys
    
- name: Set the accesskey ID
  set_fact:
    accesskey: "{{ keys.resp.accessKey }}"
  no_log: true
  
- name: Set the Secret accesskey ID
  set_fact:
    secret_accesskey: "{{ keys.resp.secretAccessKey }}"
  no_log: true
