---
  - name: Get grid authorization token
    uri:
      url: "{{ grid_admin_base_url }}/api/v3/authorize"
      method: POST
      body: {
        "username": "{{ sg_username }}",
        "password": "{{ sg_password }}",
        "cookie": false,
        "csrfToken": false
      }
      body_format: json
      validate_certs: false
    register: auth
  
  - name: Get all account data
    uri:
      url: "{{ grid_admin_base_url }}api/v3/grid/accounts?limit=500"
      method: GET
      headers:
        Authorization: "Bearer {{ auth.json.data }}"
      body_format: json
      validate_certs: false
    register: info
    
  - set_fact:
      allids: "{{ item.id }}"
    loop: "{{ info.json.data }}"
    register: allids
  
  - name: Build a list of all Tenant IDs
    ansible.builtin.set_fact:
      idlist: "{{ allids.results | map(attribute='ansible_facts.allids') | list }}"
  
  - name: Get all buckets
    uri:
      url: "{{ grid_admin_base_url }}api/v3/grid/accounts/{{ item }}/usage?includeBucketDetail=true"
      method: GET
      headers:
        Authorization: "Bearer {{ auth.json.data }}"
      body_format: json
      validate_certs: false
    loop: "{{ idlist }}"
    register: bucketlist
  
  - set_fact:
      bucketlist_temp1: "{{ bucketlist.results | map(attribute='json') | list | flatten }}"
    
  - set_fact:
      bucketlist_temp2: "{{ bucketlist_temp1 | map(attribute='data') | list | flatten }}"
      
  - set_fact:
      bucketlist_temp3: "{{ bucketlist_temp2 | map(attribute='buckets') | list | flatten }}"

  - set_fact:
      bucketlist_final: "{{ bucketlist_temp3 | map(attribute='name') | list | flatten }}"
      
      
